export enum ValidPermissions {
  create_permissions = 'CREATE_PERMISSIONS',
  create_roles = 'CREATE_ROLES',
  create_training_sessions = 'CREATE_TRAINING_SESSIONS',
  create_users = 'CREATE_USERS',
  delete_permissions = 'DELETE_PERMISSIONS',
  delete_roles = 'DELETE_ROLES',
  delete_users = 'DELETE_USERS',
  edit_training_sessions = 'EDIT_TRAINING_SESSIONS',
  edit_users_sys_admin = 'EDIT_USERS_SYS_ADMIN',
  update_permissions = 'UPDATE_PERMISSIONS',
  update_roles = 'UPDATE_ROLES',
  view_permissions = 'VIEW_PERMISSIONS',
  view_roles = 'VIEW_ROLES',
  view_training_sessions = 'VIEW_TRAINING_SESSIONS',
  view_users = 'VIEW_USERS',
}
